---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package
    package:
      name:
        - apache2
        - libapache-mod-php
      state: latest
      update_cache: yes
