---

- hosts: all
  become: true
  tasks:
    - name: install Updates
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == "Ubuntu"

- hosts: web-servers
  become: true
  tasks:
    - name: install apache2 and php package
      apt:
        name:
        - apache2
        state: latest
      tags: apache,apache2

    - name: Copying html file
      tags: apache,apache2
      copy:
        src: basic_html.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db-servers
  become: true
  tasks:
    - name: Installing mariadb in Ubuntu
      apt:
        name: mariadb-server
        state: absent
      tags: mariadb
